import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home() {
  const [newIdea, setNewIdea] = useState();
  const [verb, setVerb] = useState();

  const words = ['yield farming', 'web3', 'decentralized', 'DAO', 'leveraged'];

  const handleClick = (event) => {
    const shuffledWords = words.sort((a, b) => 0.5 - Math.random());
    setNewIdea(`${shuffledWords[0]} ${shuffledWords[1]} ${verb} to earn`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>next defi startup creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-6xl font-bold">Your Next Defi Startup</h1>

        <input
          type="text"
          className="px-4 py-3"
          placeholder="add verb here"
          onChange={(e) => setVerb(e.target.value)}
        />

        <button
          onClick={handleClick}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Click for new idea!
        </button>
        <h1 className="text-4xl font-bold underline">{newIdea}</h1>
      </main>

      <footer className={styles.footer}>
        Powered by yeildfarming.com devs
      </footer>
    </div>
  );
}
